### ISSUE TITLE
[Suggestion] Only Show Items that are Nearby

### ISSUE THREAD

**Issue by HoodBlah** [RetroTrack/OpenItemPuller#3]
Thank you for fixing the Sinytra Compat! 

I'm just here with a suggestion. Can you make it so that the items that show up on the list are only items that are in nearby inventories? It gets a bit overwhelming to see all items at once and needed to search through it all the time. 

IDK if that's a feature you already added but in forge it shows all the items in the game, not just whats nearby.

Thank you!

![2024-11-12_13 52 26](https://github.com/user-attachments/assets/5c28fb3e-05b7-485e-a833-c47aaeb1d9f7)
![2024-11-12_13 52 32](https://github.com/user-attachments/assets/fbc4bd85-8e59-4ee2-8494-6048fac7f5b2)
![2024-11-12_13 52 35](https://github.com/user-attachments/assets/d0736b7e-ee45-4248-bb7e-cd4d1168cd84)

**Comment by RetroTrack** [comment]
Well it's funny that you say that, because that feature is high on my list of plans and I am currently looking into the best approach to do it! It may need some work but i hope to implement it very soon!
