### ISSUE TITLE
Allow to pull multiple types of items at once

### ISSUE THREAD

**Issue by HoodBlah** [RetroTrack/OpenItemPuller#4]
Me Again 😈

If you select an item and then search for another item then the selection is lost. Can you make it so that the selection is saved so that we can pull out multiple different items at once instead of opening the gui to search for them over and over again?

Thanks G <3

**Comment by RetroTrack** [comment]
Hey,

Thanks again for the suggestion! I'm planning to look into it next week!

Greetings, 
Retro

**Comment by RetroTrack** [comment]
Hey, 

Sorry for the delay, school's been quite busy and a lot of changes have been made to the mod.
But a new release is planned for next week (hopefully bug free), containing multi-item selection!

As always, thanks for the suggestion!
Greetings,
Retro
