### ISSUE TITLE
Compatibility with Extended Drawers mod?

### ISSUE THREAD

**Issue by pyrodroids** [RetroTrack/OpenItemPuller#5]
Would it be possible to make it so you could see and pull items from the drawers of the Extended Drawers mod?

https://modrinth.com/mod/extended-drawers

**Comment by RetroTrack** [comment]
Hey!
It looks like its definitely worth a shot, and I try to look into it this week!

Greetings,
Retro

**Comment by RetroTrack** [comment]
Hey, 

Sorry for the delay, school's been quite busy and a lot of changes have been made to the mod.
A new release is planned for next week (hopefully bug free), which should add compatibility with the fabric storage api (and with that Extended Drawers)!

Thanks for the suggestion!
Greetings,
Retro
